dataset_config:
  memotion:
    processors:
      text_processor:
        type: bert_tokenizer
        params:
          tokenizer_config:
            type: roberta-base
            params:
              #do_lower_case: true
          mask_probability: 0
          max_seq_length: 512
