includes:
- ./text.yaml
- configs/datasets/memotion/bert.yaml
- configs/datasets/memotion/image_captions.yaml

model_config:
  unimodal_text:
    classifier:
      type: mlp
      params:
        in_dim: 768
        num_layers: 2

training:
  batch_size: 128