includes:
- ./text.yaml
- configs/datasets/memotion/roberta.yaml
- configs/datasets/memotion/image_captions.yaml
- configs/models/unimodal/roberta.yaml

model_config:
  unimodal_text:
      num_labels: 4
    classifier:
      type: mlp
      params:
        in_dim: 768
        num_layers: 2
      losses:
        - type: logit_bce

evaluation:
  metrics:
  - multilabel_macro_f1
  - multilabel_micro_f1
  - multilabel_f1


dataset_config:
  memotion:
    dataset_task: multi

training:
  batch_size: 128
  early_stop:
    criteria: offensive/multilabel_macro_f1
    minimize: false
