includes:
- ./text.yaml
- configs/models/unimodal/text_3_classes.yaml
- configs/datasets/memotion/roberta.yaml
- configs/models/unimodal/roberta.yaml

model_config:
  unimodal_text:
    classifier:
      type: mlp
      params:
        in_dim: 768
        num_layers: 2

dataset_config:
  memotion:
    dataset_task: overall_sentiment

training:
  batch_size: 128
