dataset_config:
  hateful_memes:
    use_image_captions: true
    processors:
      text_processor:
        type: multi_sentence_bert_tokenizer
    image_captions:
      train:
      - hateful_memes/defaults/image_captions/image_captioning_train.csv
      val:
      - hateful_memes/defaults/image_captions/image_captioning_dev.csv
      test:
      - hateful_memes/defaults/image_captions/image_captioning_test.csv
