dataset_config:
  hateful_memes:
    processors:
      text_processor:
        type: bert_tokenizer
        params:
          tokenizer_config:
            type: roberta-base
            params:
              do_lower_case: false
          mask_probability: 0
          max_seq_length: 128
